// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tsutvhrvfhgtayyssdxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzdXR2aHJ2ZmhndGF5eXNzZHhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4OTI1MTQsImV4cCI6MjA2NDQ2ODUxNH0.cc57Y2Y8CHg90PAboHOmEgt8oZZqkoCChT0L4dQmRlA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);